import './globals.css';
import type { Metadata } from 'next';
import SmoothScroll from '@/components/SmoothScroll'; // <--- Import the component

export const metadata: Metadata = {
  title: 'Puneet Shukla',
  description: 'Generated by Next.js',
  icons: {
    icon: '/logos/logo.png',
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      {/* NOTE: Lenis works best when applied to the whole body.
        The SmoothScroll component handles the logic.
      */}
      <body>
        <SmoothScroll />
        {children}
      </body>
    </html>
  );
}